import { createReadStream, existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const { version } = JSON.parse(readFileSync("./package.json", "utf8"));

// In dev, serve pipeline outputs straight from the output directory.
// In production (Firebase), these are deployed under /tiles/ and /boundaries/.
const TILES_DIR = resolve(__dirname, "../../output/tiles");
const BOUNDARIES_DIR = resolve(__dirname, "../../output/boundaries");

function staticJsonDir(name, mount, dir, fallback, cache = "public, max-age=3600") {
  return {
    name,
    configureServer(server) {
      server.middlewares.use(mount, (req, res, next) => {
        const fileName = decodeURIComponent(req.url.replace(/^\//, "")) || fallback;
        const filePath = join(dir, fileName);
        if (!existsSync(filePath)) return next();
        res.setHeader("Content-Type", "application/json");
        res.setHeader("Cache-Control", cache);
        createReadStream(filePath).pipe(res);
      });
    },
  };
}

export default defineConfig({
  define: {
    __APP_VERSION__: JSON.stringify(`v${version}`),
  },
  plugins: [
    react(),
    tailwindcss(),
    staticJsonDir("tiles-dev-server", "/tiles", TILES_DIR, "admin_index.json"),
    // Boundaries get regenerated by scripts/clean_boundaries.py; a long max-age here
    // silently served stale geometry after a rerun. Never cache them in dev.
    staticJsonDir("boundaries-dev-server", "/boundaries", BOUNDARIES_DIR, "", "no-store"),
  ],
});
